name: CI
on:
    pull_request: null
    push:
        branches:
            - tac
            - main
jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['7.4', '8.0', '8.1']

        name: Linting - PHP ${{ matrix.php }}
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none
                    extensions: intl
            -   run: composer install --no-progress
            -   run: composer drop-test-db
            -   run: composer create-test-db
#           -   run: composer phpstan
            -   run: composer tests
